#!/usr/bin/env node
var log = require("./lib/log.js").log;
var halolib = require("./lib/halo.js");

var ret = main();
process.exit(ret);

function main(){
	var numargs = process.argv.length;
	log("halo starting with: " + numargs);

	var srcRef  = numargs > 2 ? process.argv[numargs-1] : ".";
	var action  = numargs > 3 ? process.argv[2] : "read";
	var options = numargs > 4 ? process.argv.slice(3,numargs-1) : [];

	log("srcRef:" + srcRef);
	log("action:" + action);
	log("options:" + options);

	// load calls parser and loads srcref into mem context
	var src = halolib.load(srcRef);
	var ret;
	if(action != 'read'){
		ret = halolib.do(action,options,src);
		return ret.code ? ret.code : 0 ;
	}
	return 0;
}

