#!/usr/bin/env node
var log = require("./lib/log.js").log;
var halolib = require("./lib/halo.js");

main();

function main(){
	var numargs = process.argv.length;
	log("halo starting with: " + numargs);

	var srcRef  = numargs > 2 ? process.argv[numargs-1] : ".";
	var action  = numargs > 3 ? process.argv[2] : "read";
	var options = numargs > 4 ? process.argv.slice(3,numargs-1) : [];

	log("srcRef:" + srcRef);
	log("action:" + action);
	log("options:" + options);

	// load calls parser and loads srcref into mem context
	var src = halolib.load(srcRef);
	if(action != 'read'){
		halolib.do(action,options,src);
	}
}

